### ISSUE TITLE
Name = error in RSS Feed

### ISSUE THREAD

**Issue by una** [una/una.github.io#4]
Name appears as error in RSS

https://github.com/una/una.github.io/blob/master/feed.xml

**Comment by una** [comment]
Do you know why this might be, @jshawl

**Comment by jshawl** [comment]
How can I reproduce the issue? seems to be ok - http://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Funa.github.io%2Ffeed.xml

**Comment by una** [comment]
Hmm i don't know -- this is what I've been seeing:

https://cloudup.com/c2diY7G4G6t
