### ISSUE TITLE
Use dynamic date

### ISSUE THREAD

**Issue by hagenburger** [una/una.github.io#8]
:)

https://github.com/una/una.github.io/blob/master/_includes/footer.html#L13

**Comment by una** [comment]
Haha good idea. Dropping this here for future self-reference: http://www.dynamicsights.com/copyrightjs.html

**Comment by allypalanzi** [comment]
You can do this with jekyll, and it'll update whenever you rebuild: `{{ site.time | date: '%Y' }}`

**Comment by una** [comment]
ooh thanks for the tip @allypalanzi

**Comment by una** [comment]
Done :)
